@startuml
interface "IPubTarget`1"<out TTarget> {
    TargetType : Type <<get>>
    InvokeAsync(parameters:TRequest) : Task
    InvokeAsync(parameters:TRequest) : Task<TResult>
    BeginInvoke(parameters:TRequest) : AsyncResult
    EndInvoke(result:AsyncResult) : void
    BeginInvoke(parameters:TRequest) : AsyncResult
    EndInvoke(result:AsyncResult) : TResult?
    Invoke(parameters:TRequest) : void
    Invoke(parameters:TRequest) : TResult?
}
@enduml
